version: "3"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.server
    image: registry.heroku.com/bad-bank-matthew-cassidy/bb-server-img:latest
    container_name: bb-server-container
    command: node server.js
    env_file: ./server/.env
    environment:
      - NODE_ENV=production
    restart: always
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    image: registry.heroku.com/bad-bank-matthew-cassidy/bb-client-img:latest
    container_name: bb-client-container
    command: npm start
    depends_on:
      - server
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
