version: "3"
services:
  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - /data/db
    env_file:
      - ./server/.env
    networks:
      - app-network
      
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: worker     
    command: node server.js
    env_file: ./server/.env
    environment:
      - NODE_ENV=production
    restart: always
    networks:
      - app-network
      
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: web 
    command: npm start
    depends_on:
      - server
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
