version: "3"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: registry.heroku.com/matt-cassidy-bad-bank-5cc76dcf76cf/worker     
    command: node server.js
    env_file: ./server/.env
    environment:
      - NODE_ENV=production
    restart: always
    networks:
      - app-network
      
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: registry.heroku.com/matt-cassidy-bad-bank-5cc76dcf76cf/web 
    command: npm start
    depends_on:
      - server
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
