version: "3"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.server
    image: registry.heroku.com/bad-bank-matthew-cassidy/bb-server-img
    container_name: bb-server-container
    command: /usr/src/app/node_modules/.bin/nodemon server.js
    ports:
      - "5000:5000"
    env_file: ./server/.env
    environment:
      - NODE_ENV=production
    restart: always
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    image: registry.heroku.com/bad-bank-matthew-cassidy/bb-client-img
    container_name: bb-client-container
    command: npm start
    depends_on:
      - server
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
