version: "3"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.server
    image: bb-server-img
    container_name: bb-server-container
    command: /usr/src/app/node_modules/.bin/nodemon server.js
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file: ./server/.env
    environment:
      - NODE_ENV=production
    restart: always
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    image: bb-client-img
    container_name: bb-client-container
    command: npm start
    volumes:
      - ./client/:/usr/src/app
      - /usr/app/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  data-volume:
  node_modules:
    driver: local
