FROM node:20.11.0

RUN mkdir -p /usr/src/app/server

WORKDIR /usr/src/app/server

COPY package*.json ./

RUN npm ci --silent

COPY generateSecKey.js ./

RUN node generateSecKey.js

ENV SECRET_KEY=$SECRET_KEY

COPY . .

CMD ["node", "server.js"]
